name: Publish DevContainer Features

on:
  push:
    branches:
      - main
    paths:
      - 'features/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dev Container CLI
        run: npm install -g @devcontainers/cli

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.FEATURES_WRITE_SECRET }}" | docker login ghcr.io -u USERNAME --password-stdin

      - name: Build & Push Features
        run: |
          for feature in ./features/*; do
            if [ -d "$feature" ]; then
              echo "Publishing feature: $(basename "$feature")"
              devcontainer features publish --namespace ghcr.io/swiftstream/vsce "$feature"
            fi
          done
